/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.src.ventas.interfaces;

import com.src.ventas.service.SArticulo;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author danie
 */
public class Principal extends javax.swing.JFrame {

    RegistrarArticulo venRegistrarArticulo;
    Factura factura;
    Devolucion devolucion;
    ConsultaArticulos consultaArticulos;
    ActualizarInventario actualizarInventario;

    /**
     * Creates new form Principal
     */
    public Principal()  {
        initComponents();
        //insertar imagen
        JPanel panel = new JPanel();

        BufferedImage image;
//        try {
//            image = ImageIO.read(new File("C:\\Users\\danie\\Documents\\NetBeansProjects\\ventas\\src\\main\\java\\com\\src\\ventas\\interfaces\\swing.png"));
//
//            JLabel label = new JLabel(new ImageIcon(image));
//            panel.add(label);
//
//            // main window
//            JFrame.setDefaultLookAndFeelDecorated(true);
//            JInternalFrame frame = new JInternalFrame("JPanel Example");
//            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//            JButton boton1 = new JButton("cerrar");
//            boton1.setBounds(180, 240, 100, 30);
//            frame.add(boton1);
//            // add the Jpanel to the main window
//            frame.add(panel);
//            frame.pack();
//            frame.setVisible(true);
//            frame.setSize(jInternalFrame1.getSize());
////            jDesktopPane1.add(frame);
//            jInternalFrame1.add(frame);
//        } catch (IOException ex) {
//            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
//        }


        venRegistrarArticulo = new RegistrarArticulo();
        factura = new Factura();
        devolucion = new Devolucion();
        consultaArticulos = new ConsultaArticulos();
        actualizarInventario = new ActualizarInventario();

        consultaArticulos.setSize(jDesktopPane1.getSize());
        jDesktopPane1.add(consultaArticulos);
        this.setLocationRelativeTo(null);


        actualizarInventario.setSize(jDesktopPane1.getSize());
        jDesktopPane1.add(actualizarInventario);

        devolucion.setSize(jInternalFrame1.getSize());
        jInternalFrame1.add(devolucion);

        venRegistrarArticulo.setSize(jDesktopPane1.getSize());
        venRegistrarArticulo.setResizable(false);
        jDesktopPane1.add(venRegistrarArticulo);

        factura.setSize(jInternalFrame1.getSize());
        jInternalFrame1.add(factura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        bCrearFactura = new javax.swing.JButton();
        bDavolucion = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuGestionarCliente = new javax.swing.JMenu();
        itemGestionarCliente = new javax.swing.JMenuItem();
        menuGestionarProveedor = new javax.swing.JMenu();
        itemGestionarProveedor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemRegistrarArticulo = new javax.swing.JMenuItem();
        itemConsultarArticulo = new javax.swing.JMenuItem();
        ActualizarInventario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemCrearFactura = new javax.swing.JMenuItem();
        itemDevoluciones = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bCrearFactura.setText("Crear Factura");
        bCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearFacturaActionPerformed(evt);
            }
        });

        bDavolucion.setText("Nueva Devolución");
        bDavolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDavolucionActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(bCrearFactura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bDavolucion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDavolucion)
                    .addComponent(bCrearFactura))
                .addGap(32, 32, 32)
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(bCrearFactura)
                        .addGap(37, 37, 37)
                        .addComponent(bDavolucion))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        menuGestionarCliente.setText("Cliente");

        itemGestionarCliente.setText("Gestionar Cliente");
        itemGestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarClienteActionPerformed(evt);
            }
        });
        menuGestionarCliente.add(itemGestionarCliente);

        jMenuBar1.add(menuGestionarCliente);

        menuGestionarProveedor.setText("Proveedor");
        menuGestionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestionarProveedorActionPerformed(evt);
            }
        });

        itemGestionarProveedor.setText("Gestionar Proveedor");
        itemGestionarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarProveedorActionPerformed(evt);
            }
        });
        menuGestionarProveedor.add(itemGestionarProveedor);

        jMenuBar1.add(menuGestionarProveedor);

        jMenu3.setText("Articulo");

        itemRegistrarArticulo.setText("Registrar Artículo");
        itemRegistrarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRegistrarArticuloActionPerformed(evt);
            }
        });
        jMenu3.add(itemRegistrarArticulo);

        itemConsultarArticulo.setText("Consultar Articulos");
        itemConsultarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarArticuloActionPerformed(evt);
            }
        });
        jMenu3.add(itemConsultarArticulo);

        ActualizarInventario.setText("Actualizar inventario ");
        ActualizarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarInventarioActionPerformed(evt);
            }
        });
        jMenu3.add(ActualizarInventario);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Factura");

        itemCrearFactura.setText("Crear factura");
        itemCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearFacturaActionPerformed(evt);
            }
        });
        jMenu4.add(itemCrearFactura);

        itemDevoluciones.setText("Devoluciones");
        itemDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDevolucionesActionPerformed(evt);
            }
        });
        jMenu4.add(itemDevoluciones);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarClienteActionPerformed
        GestionarCliente ven1 = new GestionarCliente(null, true);
        ven1.show();

//       ventana2 ven2 = new ventana2();
//       jDesktopPane1.add(ven2);
//       ven2.show();
// JOptionPane.showMessageDialog(null, "Opcion panel dialogo");
//

    }//GEN-LAST:event_itemGestionarClienteActionPerformed

    private void menuGestionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestionarProveedorActionPerformed

    }//GEN-LAST:event_menuGestionarProveedorActionPerformed

    private void itemGestionarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarProveedorActionPerformed
//                jDialog1.setTitle("Dialogo Principal");
//                 jDialog1.show();
//                 jDialog1.setVisible(true);
//                 jDialog1.setSize(200, 200);

        GestionarProveedor ven1 = new GestionarProveedor(null, true);
        ven1.show();

    }//GEN-LAST:event_itemGestionarProveedorActionPerformed

    private void itemRegistrarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRegistrarArticuloActionPerformed
        actualizarInventario.setVisible(false);
        consultaArticulos.setVisible(false);
        venRegistrarArticulo.setVisible(true);
    }//GEN-LAST:event_itemRegistrarArticuloActionPerformed

    private void bCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearFacturaActionPerformed
       
            devolucion.setVisible(false);
            factura.setVisible(true);
            SArticulo art = new SArticulo();
            art.consultar(2);
       
    }//GEN-LAST:event_bCrearFacturaActionPerformed

    private void bDavolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDavolucionActionPerformed
        devolucion.setVisible(true);
        factura.setVisible(false);

    }//GEN-LAST:event_bDavolucionActionPerformed

    private void itemCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearFacturaActionPerformed
        consultaArticulos.setVisible(false);
        actualizarInventario.setVisible(false);
        venRegistrarArticulo.setVisible(false);
        devolucion.setVisible(false);
        factura.setVisible(true);
    }//GEN-LAST:event_itemCrearFacturaActionPerformed

    private void itemDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDevolucionesActionPerformed
        consultaArticulos.setVisible(false);
        actualizarInventario.setVisible(false);
        venRegistrarArticulo.setVisible(false);
        factura.setVisible(false);
        devolucion.setVisible(true);

    }//GEN-LAST:event_itemDevolucionesActionPerformed

    private void itemConsultarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarArticuloActionPerformed
        consultaArticulos.setVisible(true);
         actualizarInventario.setVisible(false);
        venRegistrarArticulo.setVisible(false);


    }//GEN-LAST:event_itemConsultarArticuloActionPerformed

    private void ActualizarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarInventarioActionPerformed
        actualizarInventario.setVisible(true);
         consultaArticulos.setVisible(false);
        venRegistrarArticulo.setVisible(false);


    }//GEN-LAST:event_ActualizarInventarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ActualizarInventario;
    private javax.swing.JButton bCrearFactura;
    private javax.swing.JButton bDavolucion;
    private javax.swing.JMenuItem itemConsultarArticulo;
    private javax.swing.JMenuItem itemCrearFactura;
    private javax.swing.JMenuItem itemDevoluciones;
    private javax.swing.JMenuItem itemGestionarCliente;
    private javax.swing.JMenuItem itemGestionarProveedor;
    private javax.swing.JMenuItem itemRegistrarArticulo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuGestionarCliente;
    private javax.swing.JMenu menuGestionarProveedor;
    // End of variables declaration//GEN-END:variables
}
